# Generated by Django 6.0.3 on 2026-03-28 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurator', '0001_initial'),
        ('my_site_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pcconfiguration',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.case', verbose_name='Case'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.gpu', verbose_name='GPU'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.motherboard', verbose_name='Motherboard'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='power_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.powersupply', verbose_name='Power Supply'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.processor', verbose_name='Processor'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='storage_devices',
            field=models.ManyToManyField(blank=True, to='my_site_app.storage', verbose_name='Storage Devices'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
