# Generated by Django 6.0.3 on 2026-04-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_initial'),
        ('my_site_app', '0007_cooler'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcconfiguration',
            name='cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.cooler', verbose_name='Cooler'),
        ),
    ]
