# Generated by Django 6.0.3 on 2026-04-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_pcconfiguration_cooler'),
        ('my_site_app', '0008_alter_cooler_options_alter_cooler_cooler_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcconfiguration',
            name='cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_site_app.cooler', verbose_name='Кулер'),
        ),
    ]
