# Generated by Django 6.0.3 on 2026-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquser',
            name='bio',
            field=models.TextField(blank=True, default='I use Build Box.', max_length=500),
        ),
        migrations.AlterField(
            model_name='uniquser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.avif', upload_to='profile_images'),
        ),
    ]
