# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_promocode(apps, schema_editor):
    PromoCode = apps.get_model('my_site_app', 'PromoCode')
    PromoCode.objects.get_or_create(
        code='BUILDBOX10',
        defaults={
            'quantity': 500,
            'discount_percent': 5,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0003_explorelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many total times this promo can be used.')),
                ('discount_percent', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='my_site_app.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('promo_code', 'user')},
            },
        ),
        migrations.RunPython(create_default_promocode, migrations.RunPython.noop),
    ]
