# Generated by Django 6.0.3 on 2026-03-31 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0004_promocode_promocodeusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Tajikistan', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
