# Generated by Django 6.0.3 on 2026-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0005_usersavedaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_hero/', verbose_name='Hero Image')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Hero Image',
                'verbose_name_plural': 'Home Hero Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
