# Generated by Django 6.0.3 on 2026-04-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0006_homeheroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('cooler_type', models.CharField(choices=[('AIR', 'Air Cooler'), ('AIO', 'AIO Liquid Cooler')], default='AIR', max_length=20, verbose_name='Cooler Type')),
                ('supported_sockets', models.CharField(max_length=200, verbose_name='Supported Sockets')),
                ('tdp_capacity', models.IntegerField(verbose_name='Supported CPU TDP (W)')),
                ('height_mm', models.IntegerField(blank=True, null=True, verbose_name='Height (mm)')),
                ('radiator_length_mm', models.IntegerField(blank=True, null=True, verbose_name='Radiator Length (mm)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, upload_to='coolers/', verbose_name='Main Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cooler',
                'verbose_name_plural': 'Coolers',
                'ordering': ['-created_at'],
            },
        ),
    ]
