# Generated by Django 6.0.3 on 2026-04-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0007_cooler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooler',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кулер', 'verbose_name_plural': 'Кулеры'},
        ),
        migrations.AlterField(
            model_name='cooler',
            name='cooler_type',
            field=models.CharField(choices=[('AIR', 'Воздушный кулер'), ('AIO', 'Жидкостное охлаждение')], default='AIR', max_length=20, verbose_name='Тип кулера'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='height_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='image',
            field=models.ImageField(blank=True, upload_to='coolers/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='radiator_length_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина радиатора (мм)'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='supported_sockets',
            field=models.CharField(max_length=200, verbose_name='Поддерживаемые сокеты'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='tdp_capacity',
            field=models.IntegerField(verbose_name='Поддерживаемый TDP процессора (Вт)'),
        ),
    ]
