# Generated by Django 6.0.3 on 2026-04-02 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdminLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram user ID')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Telegram username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('receive_new_order_notifications', models.BooleanField(default=True, verbose_name='Receive new order notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_admin_link', to=settings.AUTH_USER_MODEL, verbose_name='Admin user')),
            ],
            options={
                'verbose_name': 'Telegram admin link',
                'verbose_name_plural': 'Telegram admin links',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='TelegramOrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NEW_ORDER', 'New order')], default='NEW_ORDER', max_length=30, verbose_name='Event type')),
                ('message_text', models.TextField(verbose_name='Message text')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Delivery status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_order_bot.telegramadminlink', verbose_name='Telegram admin link')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Telegram order notification',
                'verbose_name_plural': 'Telegram order notifications',
                'ordering': ['delivery_status', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('admin_link', 'order', 'event_type'), name='uniq_tg_order_event_per_admin')],
            },
        ),
    ]
